### ISSUE TITLE
Can't remove all entries on the list

### ISSUE THREAD

**Issue by hanyuwei70** [FoxAuth/FoxAuth#11] opened 2018-10-28 17:43 UTC
**Describe the bug**
When I tried to delete all entries, it can't be done and always left a blank entry.

**To Reproduce**
1. Go to 'secret token'
2. Click on 'cross of the last entry'
3.Confirm The warning

**Expected behavior**
Last entry should be deleted

**Desktop:**
 - OS: Windows 10 1803
 - Firefox 63
- Plugin No version number available

**Comment by Riajyuu** [comment] 2018-10-29 00:25
> always left a blank entry

By design

**Comment by Riajyuu** [comment] 2018-10-29 07:49
I did found something else.

**Comment by Riajyuu** [comment] 2018-10-30 02:22
shall be fixed in 5b4eee522977654cc9b2a1ef1dc14db282f082ab and f9ee1d6b3364ada98e9f09dedc5de43833b00899

**Closed as completed by Riajyuu** 2018-10-30 02:22 UTC
Labels: bug, good first issue, P1
